[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./deployments/testnet.json" }]

# Optimizer settings for accurate gas measurements
optimizer = true
optimizer_runs = 200
via_ir = true

# Testing configuration
verbosity = 2
gas_reports = ["*"]
gas_snapshots = true

# Remappings for cleaner imports
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

# RPC endpoints
[rpc_endpoints]
fluent-testnet = "https://rpc.testnet.fluent.xyz"